name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: release
      BINARY: pgn_parser

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake make g++ python3-pytest && pip install chess
    
    - name: Create build directory
      run: mkdir -p build
    
    - name: Run CMake
      run: cmake .. -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      working-directory: build
    
    - name: Run Make
      run: make -j$(nproc)
      working-directory: build
    
    - name: List build directory
      run: ls -la
      working-directory: build
    
    - name: Prepare pytest directory
      run: mkdir -p pytest
    
    - name: Check if binary exists
      run: test -f build/${{ env.BINARY }}
    
    - name: Copy binary for testing
      run: cp build/${{ env.BINARY }} pytest/
    
    - name: Run tests and generate report
      run: cd pytest && python3 generate_test_data.py && python3 -m pytest ./Test*.py --junitxml=results.xml
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: pytest/results.xml

    - name: Clean up
      run: git clean -xdf
  
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo $SSH_PRIVATE_KEY
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Clone public repository
      run: |
        cd ..
        mkdir public-repo
        git clone git@github.com:tho-nk/pgn.git public-repo
        cd public-repo
        rm -rf *

    - name: Copy files to public repository
      run: |
        cp -R * ../public-repo/
        mkdir -p ../public-repo/.github/workflows/
        cp -R .github/workflows/pgn_public.yml_ ../public-repo/.github/workflows/pgn.yml
      continue-on-error: true

    - name: Get latest commit message from the source branch
      id: get_commit_msg
      run: |
        # Fetch the source branch and the pull request
        git fetch origin +refs/heads/${{ github.head_ref }}:refs/remotes/origin/${{ github.head_ref }}
        git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge
        
        # Checkout the source branch of the PR
        git checkout ${{ github.head_ref }}  # Checkout the source branch
        
        # Get the latest commit message
        echo "Latest commit message:"
        git log -1 --pretty=%B > ../commit_msg.txt  # Store the latest commit message in a file
        cat ../commit_msg.txt  # Output the commit message for logging purposes

    - name: Commit and Push Changes
      run: |
        cd ../public-repo
        git config --global user.email "tho.nk1325@gmail.com"
        git config --global user.name "ugitho"
        
        # Check for changes
        if [ -n "$(git status --porcelain)" ]; then
          BRANCH_NAME=${GITHUB_REF##*/}  # Get the current branch name
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            BRANCH_NAME=${{ github.head_ref }}  # Get the source branch of the PR
          fi
            echo "Current branch name: $BRANCH_NAME"
          
          # Create a new branch if it doesn't exist
          if git show-ref --verify --quiet refs/heads/"$BRANCH_NAME"; then
              echo "Branch $BRANCH_NAME already exists. Switching to it."
              git checkout "$BRANCH_NAME"
          else
              echo "Creating new branch $BRANCH_NAME."
              git checkout -b "$BRANCH_NAME"  # Create a new branch with the current branch name
          fi

          # Use the commit message from the private repo
          git add .
          git commit -m "$(cat ../commit_msg.txt)"
          git push -u origin "$BRANCH_NAME"  # Push to the branch
        else
          echo "No changes to commit, skipping."
        fi
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

# Generate SSH key
# `ssh-keygen -t ed25519 -C "tho.nk1325@gmail.com" -f github_action_key`
# This command will create two files:

# github_action_key: The private key
# github_action_key.pub: The public key

# Add github_action_key.pub content to github settings -> ssh and gpg key
# Add github_action_key content as a private key when running action
# -> repositoy settings -> Secrets and variables -> Actions -> Repository secrets (SSH_PRIVATE_KEY)

