name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: release
      BINARY: pgn_parser

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake make g++ python3-pytest
    
    - name: Create build directory
      run: mkdir -p build
    
    - name: Run CMake
      run: cmake .. -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      working-directory: build
    
    - name: Run Make
      run: make -j$(nproc)
      working-directory: build
    
    - name: List build directory
      run: ls -la
      working-directory: build
    
    - name: Prepare pytest directory
      run: mkdir -p pytest
    
    - name: Check if binary exists
      run: test -f build/${{ env.BINARY }}
    
    - name: Copy binary for testing
      run: cp build/${{ env.BINARY }} pytest/
    
    - name: Run tests and generate report
      run: cd pytest && python3 -m pytest ./TestParserPGN.py --junitxml=results.xml
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: pytest/results.xml

    - name: Clean up
      run: git clean -xdf
  
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo $SSH_PRIVATE_KEY
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Clone public repository
      run: |
        cd ..
        mkdir public-repo
        git clone git@github.com:tho-nk/pgn.git public-repo

    - name: Copy files to public repository
      run: |
        cp -R * ../public-repo/
      continue-on-error: true

    - name: Commit and Push Changes
      run: |
        cd ../public-repo
        git config --global user.email "tho.nk1325@gmail.com"
        git config --global user.name "ugitho" 
        git add .
        git commit -m "Update static files" -a
        git push origin main  # Replace 'main' with the branch you want to push to
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
