name: PR_MAIN

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # Specify the Docker container to use
    runs-on: ubuntu-latest
    container:
      image: iainttho/ubuntu:24.10.github_ci # Your custom Docker image

    env:
      BUILD_TYPE: release
      BINARY: pgn_parser

    steps:
    - uses: actions/checkout@v4
  
    - name: Create build directory
      run: mkdir -p build
    
    - name: Run CMake
      run: cmake .. -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      working-directory: build
    
    - name: Run Make
      run: make -j$(nproc)
      working-directory: build
    
    - name: List build directory
      run: ls -la
      working-directory: build
    
    - name: Prepare pytest directory
      run: mkdir -p pytest
    
    - name: Check if binary exists
      run: test -f build/${{ env.BINARY }}
    
    - name: Copy binary for testing
      run: cp build/${{ env.BINARY }} pytest/
    
    - name: Run tests and generate report
      run: cd pytest && python3 generate_test_data.py && python3 -m pytest ./Test*.py --junitxml=results.xml
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: pytest/results.xml

# Generate SSH key
# `ssh-keygen -t ed25519 -C "tho.nk1325@gmail.com" -f github_action_key`
# This command will create two files:

# github_action_key: The private key
# github_action_key.pub: The public key

# Add github_action_key.pub content to github settings -> ssh and gpg key
# Add github_action_key content as a private key when running action
# -> repositoy settings -> Secrets and variables -> Actions -> Repository secrets (SSH_PRIVATE_KEY)

